# Generated by Django 5.1 on 2024-10-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('qtext', models.CharField(default='null', max_length=50)),
                ('answer', models.CharField(default='null', max_length=50)),
                ('op1', models.CharField(default='null', max_length=50)),
                ('op2', models.CharField(default='null', max_length=50)),
                ('op3', models.CharField(default='null', max_length=50)),
                ('op4', models.CharField(default='null', max_length=50)),
                ('subject', models.CharField(default='null', max_length=50)),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('username', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='null', max_length=40)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=40)),
                ('mobno', models.IntegerField(default=0)),
                ('emailid', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
